.nolist
#include "ti83plus.inc"
.list
checksum        equ     appBackUpScreen
ptrData         equ     checksum+2
dataSize        equ     ptrData+4
.org userMem-2
        .db 0BBh,6Dh

        ld hl,sCode
        rst 20h
        bcall(_chkFindSym)
        ret c
        ld a,b
        or a
        ret nz

        ex de,hl
        ld c,(hl)
        inc hl
        ld b,(hl)
        inc hl
        inc hl ;skip AsmPrgm token
        inc hl
        dec bc ;ignore AsmPrgm token
        dec bc
        ld (ptrData),hl
        ld (dataSize),bc

        ld hl,0
        ld (checksum),hl
        bcall(_clrLCDFull)

        ld hl,linkHandler
        call APP_PUSH_ERRORH

        ;send _large_ header packet
        ld a,23h
        bcall(_SendAByte)
        ld a,06h
        bcall(_SendAByte)
        ld a,0FFh
        bcall(_SendAByte)
        ld a,0FFh
        bcall(_SendAByte)
        ld bc,9090h-867Dh ;put junk from ioData to 9090h
sendStartLoop:
        push bc
        call sendByte
        pop bc
        dec bc
        ld a,b
        or c
        jr nz,sendStartLoop

        ;Send the jump to userMem
        ld a,0C3h
        call sendByte
        ld a,95h
        call sendByte
        ld a,9Dh
        call sendByte

        ;Send junk to get us to userMem
        ld bc,userMem-9093h
sendJunkLoop:
        push bc
        xor a
        call sendByte
        pop bc
        dec bc
        ld a,b
        or c
        jr nz,sendJunkLoop

        ;Send our code
        ld hl,(ptrData)
        ld bc,(dataSize)
sendCodeLoop:
        push hl
        push bc
        ld a,(hl)
        call sendByte
        pop bc
        pop hl
        inc hl
        dec bc
        ld a,b
        or c
        jr nz,sendCodeLoop

        ;Send enough 90h's to overwrite the stack
        ;This is the space between userMem+dataSize and 0FFFFh
        ld hl,userMem
        ld de,(dataSize)
        add hl,de
        ex de,hl
        ld hl,0
        or a
        sbc hl,de
        ld b,h
        ld c,l
sendStackReplacementLoop:
        push bc
        ld a,90h
        call sendByte
         pop bc
         push bc
         ld h,b
         ld l,c
         ld bc,0
         ld (curRow),bc
         bcall(_disphl)
        pop bc
        dec bc
        ld a,b
        or c
        jr nz,sendStackReplacementLoop

        ;Keep sending bytes until the checksum becomes zero
        ;(This is at most 257 bytes, so it should be okay)
fixChecksumLoop:
        ld hl,0
        ld bc,(checksum)
        or a
        sbc hl,bc
        ld a,h
        or a
        ld a,0FFh
        scf
        jr nz,lotsMoreToGo
        or a
        ld a,l
lotsMoreToGo:
        push af
        call sendByte
         ld hl,1
         ld (curRow),hl
         ld hl,(checksum)
         bcall(_disphl)
        pop af
        jr c,fixChecksumLoop

        ;Keep sending zeroes until the other calculator tries to ACK
        ; (at which point _SendAByte fails and we hope _Get4BytesNC doesn't)
        ld hl,sendOverHandler
        call APP_PUSH_ERRORH
         ld hl,0
         ld (checksum),hl
sendingZeroesLoop:
         ld hl,2
         ld (curRow),hl
         ld hl,(checksum)
         bcall(_disphl)
        xor a
        bcall(_SendAByte)
         ld hl,(checksum)
         inc hl
         ld (checksum),hl
        jr sendingZeroesLoop
sendOverHandler:
        bcall(_Get4BytesNC)
linkHandler:
        call APP_POP_ERRORH
        bcall(_newLine)
        res indicOnly,(iy+indicFlags)
        ret
sendByte:
        ld hl,(checksum)
        ld d,0
        ld e,a
        add hl,de
        ld (checksum),hl
        bcall(_SendAByte)
        ret
sCode:  .db ProgObj,"CODE",0
.end
end
