"""Build a self-contained MicroPython script that the Pico can run via
`mpremote run` to push a program to the calc and (optionally) request it
back and byte-compare.

The .8Xp payload is read on the host and inlined as a bytes literal so the
generated script doesn't need filesystem access on the Pico side.

Usage:
  python tools/build_e2e.py push     programs/flappy_bird/FLAPPY.8xp
  python tools/build_e2e.py roundtrip programs/flappy_bird/FLAPPY.8xp
  python tools/build_e2e.py listen   [NAME [TYPE_HEX]]
  python tools/build_e2e.py bridge   [NAME [TYPE_HEX]]

Writes the generated script to stdout.
"""

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT / "tools"))

from extract_8xp import read_8xp


PUSH_TEMPLATE = '''\
# generated by tools/build_e2e.py -- do not edit
import sys
import dbus

NAME = {name!r}
PAYLOAD = {payload!r}
LOCKED = {locked!r}

print("e2e push: name={{}} locked={{}} bytes={{}}".format(NAME, LOCKED, len(PAYLOAD)))
ok = dbus.put_prog_83p(NAME, PAYLOAD, locked=LOCKED, quiet=True)
if not ok:
    print("FAIL: put_prog_83p returned False")
    sys.exit(1)
print("OK: pushed {{}} ({{}} bytes)".format(NAME, len(PAYLOAD)))
'''


ROUNDTRIP_TEMPLATE = '''\
# generated by tools/build_e2e.py -- do not edit
import sys
import dbus
from vartypes import T_PROG, T_PROG_LOCKED, prog_name

NAME = {name!r}
PAYLOAD = {payload!r}
LOCKED = {locked!r}

print("e2e roundtrip: name={{}} locked={{}} bytes={{}}".format(NAME, LOCKED, len(PAYLOAD)))

ok = dbus.put_prog_83p(NAME, PAYLOAD, locked=LOCKED, quiet=True)
if not ok:
    print("FAIL: put_prog_83p returned False")
    sys.exit(1)
print("pushed {{}}".format(NAME))

type_id = T_PROG_LOCKED if LOCKED else T_PROG
got = dbus.req_var(type_id, prog_name(NAME), calc_machine=0x73)
if got is None:
    print("FAIL: req_var returned None")
    sys.exit(2)
hdr, data = got
if data != PAYLOAD:
    print("FAIL: round-tripped bytes differ")
    print("  sent_len={{}} got_len={{}}".format(len(PAYLOAD), len(data)))
    # find first divergence for the log
    n = min(len(PAYLOAD), len(data))
    for i in range(n):
        if PAYLOAD[i] != data[i]:
            print("  first diff at byte {{}}: sent=0x{{:02X}} got=0x{{:02X}}".format(
                i, PAYLOAD[i], data[i]))
            break
    sys.exit(3)
print("OK: roundtrip byte-identical ({{}} bytes)".format(len(PAYLOAD)))
'''


LISTEN_TEMPLATE = '''\
# generated by tools/build_e2e.py -- do not edit
import dbus

NAME = {name!r}
TYPE = {type_!r}

print("listen: name={{}} type={{}}".format(NAME, hex(TYPE) if TYPE is not None else None))
dbus.listen_loop(name=NAME, expected_type=TYPE)
'''


BRIDGE_TEMPLATE = '''\
# generated by tools/build_e2e.py -- do not edit
import bridge

bridge.run(name={name!r}, expected_type={type_!r})
'''


def main():
    if len(sys.argv) < 2 or sys.argv[1] not in ("push", "roundtrip", "listen", "bridge"):
        sys.stderr.write(
            "usage: build_e2e.py {push|roundtrip} <file.8xp>\n"
            "       build_e2e.py listen [NAME [TYPE_HEX]]\n"
            "       build_e2e.py bridge [NAME [TYPE_HEX]]\n")
        sys.exit(2)

    mode = sys.argv[1]
    if mode in ("listen", "bridge"):
        name = sys.argv[2] if len(sys.argv) > 2 else None
        type_ = int(sys.argv[3], 16) if len(sys.argv) > 3 else None
        tmpl = LISTEN_TEMPLATE if mode == "listen" else BRIDGE_TEMPLATE
        sys.stdout.write(tmpl.format(name=name, type_=type_))
        return

    if len(sys.argv) != 3:
        sys.stderr.write("usage: build_e2e.py {push|roundtrip} <file.8xp>\n")
        sys.exit(2)
    name, type_id, locked, payload = read_8xp(sys.argv[2])
    tmpl = PUSH_TEMPLATE if mode == "push" else ROUNDTRIP_TEMPLATE
    sys.stdout.write(tmpl.format(name=name, payload=payload, locked=locked))


if __name__ == "__main__":
    main()
